# screen properties
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# player drawing and collision
PLAYER_RADIUS = 20
LINE_WIDTH = 2

#shooting properties
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# player movement speed
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_ACCELERATION = 600
PLAYER_FRICTION = 0.991
# asteroids properties
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS *ASTEROID_KINDS

